# Generated by Django 4.1.11 on 2023-09-06 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('username', models.CharField(max_length=100)),
                ('mail', models.EmailField(max_length=254, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issued', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=1000)),
                ('recipe', models.TextField()),
                ('moderation', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes_app.author')),
            ],
            options={
                'ordering': ['-issued'],
            },
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-issued'], name='recipes_app_issued_b623a6_idx'),
        ),
    ]
